apiVersion: v1
kind: Namespace
metadata:
  name: database-instances-fr
---
apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: birds-database
  namespace: database-instances-fr
spec:
  memory: 800Mi
  cpu: "0.8"
  pgConfig:
    dbname: birds-database
    username: pgadmin
    appUser: admin
  highAvailability:
    enabled: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    servicebinding.io/controller: "true"
    resourceclaims.services.apps.tanzu.vmware.com/controller: "true"
  name: birds-servicebinding-controller-postgres-reader
rules:
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgres
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: birds-app-operator-reader
  labels:
    apps.tanzu.vmware.com/aggregate-to-app-operator-cluster-access: "true"
rules:
- apiGroups:
  - sql.tanzu.vmware.com
  resources:
  - postgres
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ClusterInstanceClass
metadata:
  name: tanzu-postgres
spec:
  description:
    short: Tanzu Postgres instances with a postgresql engine
  pool:
    group: sql.tanzu.vmware.com
    kind: Postgres
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaimPolicy
metadata:
  name: birds-developer-in-dev-tap-can-claim-any-pgsql
  namespace: database-instances-fr
spec:
  consumingNamespaces:
  - dev-tap
  subject:
    group: sql.tanzu.vmware.com
    kind: Postgres
---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: birds-tanzu-postgresql-database
  namespace: dev-tap
spec:
  ref:
    apiVersion: sql.tanzu.vmware.com/v1
    kind: Postgres
    name: birds-database
    namespace: database-instances-fr
