apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: birds-springboot-postgresql
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/name: birds
    app.kubernetes.io/part-of: micropets-app
    micropets/kind: backend
    apps.tanzu.vmware.com/has-tests: "true"
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  serviceAccountName: tap-default
  source:
    git:
      url: https://github.com/bmoussaud/micropets-birds-springboot-postgresql
      ref:
        branch: main
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: postgres
  serviceClaims:
    - name: birds-database
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: micropets-dev-tanzu-postgresql-database
  params:
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: bmoussaud
    - name: gitops_repository_name
      value: micropets-app-gitops
    - name: port
      value: 8080
    - name: observability
      value: false         
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
